config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]

  resources :contacts
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {minimum: 7}, uniqueness: {scope: :body}

  validates :body, presence: true

  def body_snippet
    body.length > 100 ? body[0..99] + "..." : body
  end

  def self.search(search)
    where("title ILIKE ? OR body ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: VALID_EMAIL_REGEX

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in!" unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), notice: "comment created"
    else
      flash[:alert] = "comment invalid"
      render "/posts/show"
    end
  end

  def destroy
    post_obj = Post.find params[:post_id]
    comment = post_obj.comments.find params[:id]
    comment.destroy
    redirect_to post_path(post_obj)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all
    end
    @posts = @posts.page(params[:page]).per(10)
  end

  def create
    post_params = params.require(:post).permit(:title, :body)
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "aksuyfg"
    else
      flash[:alert] = "FAIL"
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    post_params = params.require(:post).permit(:title, :body)

    if @post.update post_params
      redirect_to @post, notice: "iahv"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "WAKA"
  end

  private

  def find_post
    @post = Post.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed In!"
    else
      flash[:alert] = "Wrong Credentials!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

  private

  def redirect_if_loggedin
    redirect_to root_path, notice: "Already logged in" if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                                :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      # we log the user in by setting the session :user_id to the user's id
      # in our database so we can identify the user who is logged in by their id
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<h1>Poopie</h1>

app/views/home/index.html.erb
<h1></h1>
<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">

<img src="http://orig08.deviantart.net/4b7d/f/2012/188/2/b/welcome_gif_by_4everlaugh-d56crsq.gif" alt="" />
<i class="em em-poop"></i>
<img src="http://i.imgur.com/b75Tmho.gif" alt="" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path %> |
  <%= link_to "All Posts", posts_path %> |
  <%= link_to "New Post", new_post_path %> |
  <% if user_signed_in? %>
    Hello <%= current_user.first_name %>,
    <%= link_to "Log out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_path %>
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= @post.errors.full_messages.join(", ") %>

<%= render "post_form" %>

app/views/posts/index.html.erb
<h1>Current posts:</h1>

<div>
  <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Requests" %>
  <%= submit_tag "Search" %>
  <% end %>
</div> <br>

<% @posts.each do |post| %>
  <div class="">
    <%= link_to post.title, post_path(post) %>
  </div> <br>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>Create a new post:</h1>

<%= render "post_form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %>:</h1>

<%= @post.body %> <br> <br>

<%= link_to "Edit", edit_post_path %>
<%= link_to "Delete", post_path, method: :delete, data: {confirm: "U sure about this holmes?"} %>

<hr>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

<h2>Comments:</h2>
<% @poop = 0 %>
<% @post.comments.each do |com| %>
  Comment <%= @poop += 1 %>: <%= com.body %>
  <%= button_to "Delete comment", [@post, com], method: :delete, data: {confirm: "U sure about this holmes?"} %>
  <hr>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Create an Account" %>
  </div>
<% end  %>